services:
  - type: web
    plan: free
    name: AutoRenameBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Codeflix-Bots/AutoRenameBot.git
    branch: main
    autoDeploy: True
    envVars:
      - key: BOT_TOKEN
        sync: True
      - key: API_ID
        sync: True
      - key: API_HASH
        sync: True
      - key: FORCE_SUB
        sync: True
      - key: LOG_CHANNEL
        sync: True
      - key: DB_NAME
        sync: True
      - key: DB_URL
        sync: True
      - key: START_PIC
        sync: True
      - key: ADMIN
        sync: false
      - key: WEBHOOK
        sync: false
